-d C:\Users\PABLO-LAP-LENOVO\Documents\gti programing projects\hdl\UartSelector\SystemVerilog\UART_selector\impl\gwsynthesis\UART_selector.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst C:\Users\PABLO-LAP-LENOVO\Documents\gti programing projects\hdl\UartSelector\SystemVerilog\UART_selector\src\UART_selector.cst
-cfg C:\Users\PABLO-LAP-LENOVO\Documents\gti programing projects\hdl\UartSelector\SystemVerilog\UART_selector\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
